interface _OctokitUser
  def login: () -> String
end

interface _OctokitRepo
  def name: () -> String
  def updated_at: () -> Time
  def default_branch: () -> String
end

interface _OctokitWorkflowRun
  def conclusion: () -> String?
end

interface _OctokitWorkflowRuns
  def workflow_runs: () -> Array[_OctokitWorkflowRun]
end

module Octokit
  class Client
    def user: (?(Integer | String) user, ?Hash[untyped, untyped] options) -> _OctokitUser
            | ...

    def repos: (String, ?type: String) -> Array[_OctokitRepo]

    def workflow_runs: (String, ?per_page: Integer, ?branch: String) -> _OctokitWorkflowRuns

    def pull_requests: (String, ?state: String) -> Array[untyped]
  end
end
