interface _OctokitContent
  def name: () -> String
  def path: () -> String
  def content: () -> String
end

interface _OctokitUser
  def login: () -> String
end

interface _OctokitRepo
  def name: () -> String
  def updated_at: () -> Time
  def default_branch: () -> String
end

interface _OctokitWorkflowRun
  def head_sha: () -> String
  def conclusion: () -> String?
end

interface _OctokitWorkflowRuns
  def workflow_runs: () -> Array[_OctokitWorkflowRun]
end

module Octokit
  class NotFound < StandardError
  end

  class Client
    def initialize: (?access_token: String) -> void

    def user: () -> _OctokitUser

    def repos: (String, ?type: String) -> Array[_OctokitRepo]

    def get: (String, ?branch: String, ?per_page: Integer) -> _OctokitWorkflowRuns

    def pull_requests: (String, ?state: String) -> Array[untyped]

    def contents: (String, ?path: String) -> untyped

  end
end
