---

plugins:
- rubocop-numbered-params
- rubocop-rake
- rubocop-rbs_inline
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 30

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SpecFilePathFormat:
  CustomTransform:
    GitHub: github

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/ItBlockParameter:
  Enabled: false

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RedundantTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
